<?php
    $customerToken = $block->getCustomerTokenForBlock();
?>
<!--<div id="payment-container">-->
<!--    <div id="payment-form-container">-->
<!--        <script type="application/json">-->
<!--            {-->
<!--                "payButtonText": "Pay €10.99 now!",-->
<!--                "language": "en",-->
<!--                "fontFamily": "Helvetica",-->
<!--                "customerToken": "--><?//= $customerToken ?><!--",-->
<!--                "apiHost": "connect2.payxpert.com"-->
<!--            }-->
<!--        </script>-->
<!--    </div>-->
<!--</div>-->
<b>Seamless payment 1.2.2-7-iframe</b>
<iframe id="iframe" src="" frameborder="0" name="payxpert_iframe"></iframe>
<script>
    window.frames['payxpert_iframe'].document.body.innerHTML = '<div id="payment-container"></div>\x3Cscript async="true" src="https://connect2.payxpert.com/payment/<?= $customerToken ?>/connect2pay-seamless-v1.2.1.js" data-mount-in="#payment-container" integrity="sha384-KoRUPIW3yZfYzkFzrA1D2/qUKXpnNoiyflE7W0V4kDhJtuQJn8BbwkqrzRPdsXx3" crossorigin="anonymous">\x3C/script>\x3Cscript>function receive(event) {console.log("Received Message : " + event.data);}window.addEventListener("postMessage", receive);\x3C/script>';


</script>
<!--<script>-->
<!--    require.config({-->
<!--        map: {-->
<!--            '*': {-->
<!--                //'customjs':  'https://connect2.payxpert.com/payment/--><?////= $customerToken ?>/////connect2pay-seamless-v1.2.2.js'
<!--//                'seamlessjs': 'Payxpert_Connect2Pay/js/connect2pay-seamless-v1.2.2'-->
<!--//            }-->
<!--//        }-->
<!--//    });-->
<!--//</script>-->
<!--//<script type="text/x-magento-init">-->
<!--//    {-->
<!--//        "*": {-->
<!--//            "Payxpert_Connect2Pay/js/example":{}-->
<!--//        }-->
<!--//    }-->
<!--//</script>-->
<script async="true" src="https://connect2.payxpert.com/payment/<?= $customerToken ?>/connect2pay-seamless-v1.2.1.js"
        data-mount-in="#payment-container"
        integrity="sha384-XgvSgy5+BtvDa0F+xF0j71WIh3X9yF+BEe4inZw0bfEnBQtqAy+pcckMcXqFZwO6" crossorigin="anonymous">

</script>
