<script>
    console.log("I'm loaded!");
    var require = {
        "baseUrl": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('/') ?>"
    };

</script>
<script>
    require.config({
        map: {
            '*': {
                //'customjs':  'https://connect2.payxpert.com/payment/<?//= $customerToken ?>///connect2pay-seamless-v1.2.2.js'
                'seamlessjs': 'Payxpert_Connect2Pay/js/connect2pay-seamless-v1.2.2'
            }
        }
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Payxpert_Connect2Pay/js/example":{}
        }
    }
</script>
